### ISSUE TITLE
asking for instructions !!!

### ISSUE THREAD

**Issue by nxs5899** [theamrzaki/text_summurization_abstractive_methods#1]
Hi Amrzaki!

I read your blogs on Medium, they are very good. I am new to text summarization and was wondering how to run the pointer-generator model with coverage on new data, I mean how to use it to summarize new articles?
 your help is appreciated.

**Comment by theamrzaki** [comment]
thanks for your interest ... in the coming couple of days isA .. i would post here on github the steps how to use the data for this notebook .. and how to prepare your own data for it

**Comment by theamrzaki** [comment]
[Link for processing data](https://github.com/theamrzaki/text_summurization_abstractive_methods/tree/master/Implementation%20B%20(Pointer%20Generator%20seq2seq%20network)/PreProcessData)

this is a python code to run locally , to generate the required data in the correct format for both model 4 & model 5 , it requires your data to be in a csv format , having 2 columns (content , summary) , it generates the output in chunks of binary data and a file containing vocab , please try it and tell me your review

**Comment by nxs5899** [comment]
thanks for the update. however, my question is that: how can I use the trained model to summarize new documents, other than CNN/DAILY MAIL? a completely new document that I have no summary for it.
appreciate your feedback.

**Comment by theamrzaki** [comment]
You can use my new script and provide yourown documents in a csv format .. and it would process your data in the required binary format to be read by the notebook

**Comment by theamrzaki** [comment]
@nxs5899 I believe your issue has been solved .. however whenever you need any assistance you are more than welcome to open a new issue
