### ISSUE TITLE
Model_3.ipynb (util.py)

### ISSUE THREAD

**Issue by swayam01** [theamrzaki/text_summurization_abstractive_methods#3]
thanks for the great work, i see get_init_embedding wrapper function has embedding pickle file as glove/model_glove_300.pkl. want to confirm from you - is it just the pickle conversion of glove/glove.6B.300d.txt file or somethinfg else.

Also want to know what is the difference between loading .vec file or .pkl file as embedding vector

**Comment by theamrzaki** [comment]
I think you are working on model 2

and yes , this is a pickle conversion of the glove/glove.6B.300d.txt
here is [the link](https://drive.google.com/open?id=1qxBKLczcqA5Y682SpZhWX6Z_COrNjMDj) for both glove/glove.6B.300d.txt & my pickle file

and for the .vec & .pkl 
they both serve the same concept for word2vector (a dictionary for words , where each word is represented by a vector) , the only difference is how you load them , nothing more .

Hope this helps

**Comment by swayam01** [comment]
thank a lot for the help.

**Comment by theamrzaki** [comment]
Any time
